### ISSUE TITLE
Breaking namespace issue

### ISSUE THREAD

**Issue by lucasvdh** [globalcitizen/php-iban#101]
Version `2.8.0` should have been `3.0.0` because the change in namespace is a **breaking change**. This almost broke my production environment and was only caught due to automated tests.

Please remove version `2.8.0` and add a new version `3.0.0` which contains this namespace change so it doesn't break other projects.

**Comment by globalcitizen** [comment]
Thanks for letting me know about your issue.

I think the project is quite clear that we don't recommend OO at all, and
you are using it in production. That is not recommended.

A mid-level version increment seemed appropriate for something only
affecting one interface. No production updates should be done without
tests. While I take your point and agree that perhaps a major number would
have been better, I cannot agree to go back and undo history. The die is
cast.

Thanks for your well meaning contribution, regardless, and I apologise for
the hassle. However, please understand I am spread very thin on many
projects not visible here and cannot be all things to all people.

**Comment by lucasvdh** [comment]
Hi @globalcitizen, thanks for the reply. 

It's really no issue for me, just that it might cause some for other people. 

However I do not agree that, as you say, the die is cast. There are other options for fixing this like for example: removing the namespace in a version `2.8.1` and re-adding it in version `3.0.0`. Because if someone requires this package at version `2.x` the expectation would be that it would keep working regardless of minor version increments. Even if the use of the OO version is discouraged it is still a supported feature in the current version.

If the OO version is not to be used at all it should be deprecated in version `2.x` and removed in `3.x`. But that is just my humble opinion. If I can do anything to help, let me know.

Huge thanks for this package btw!
