### ISSUE TITLE
Strangeness on registry.txt in Timor-Leste

### ISSUE THREAD

**Issue by DanyCorbineauBappli** [globalcitizen/php-iban#103]
Hello,

during our application testing we have detected an anomaly on Timor-Leste BBAN check.
After search we have analysed this project.

On the file "registry.txt" we have detected a strangeness.
The "bban_format_regex" of "Timor-Leste" (TL) contain spaces. All other "bban_format_regex" does'nt contain spaces.
It's normal that "bban_format_regex" contain spaces ?

If not, how can-we correct that ?
Do we need to create a pull request or we leave it to you ?

Thanks you for your response. Have a good day.

**Comment by globalcitizen** [comment]
```
php-iban/utils$ php validate-list.php example-ibans/tl-ibans
TL380080012345678910157 ... ok
TL38 0030 000000033579760 ... ok
```

Seems fine to me. What is the sample IBAN you are looking at?

**Comment by DanyCorbineauBappli** [comment]
Hello,
I have tested the new version. This corrects the problem.

Thank you very much for the correction.

Have a good week.

**Comment by globalcitizen** [comment]
Magnifique!
