### ISSUE TITLE
2.8.x is not compatible

### ISSUE THREAD

**Issue by mahkali** [globalcitizen/php-iban#104]
When I first loaded this package i used `composer require  globalcitizen/php-iban`. This placed an entry in my composer.json as following: ` "globalcitizen/php-iban": "^2.6",`

Whenever run composer update, composer updates this package within the range of 2.x by default. After updating composer today, i noticed that my application broke because of the introduction of namespaces in 2.8.0.

I would like to suggest to release 3.0 and remove 2.8.x so anyone that assumes SemVer will not have a breaking application.

**Comment by globalcitizen** [comment]
I am not familiar with composer.

If you are suggesting a version bump, I can do that on the next release, but I am not sure why 3.x should be any different to 2.x with respect to brokenness. Can you clarify?

**Comment by globalcitizen** [comment]
Oh are you suggesting the namespacing change in 2.8 broke things? OK. Well, you are the second person to say that. I will release v3 then.

**Comment by globalcitizen** [comment]
Hopefully fixed with [v3.0.0 release](https://github.com/globalcitizen/php-iban/releases/tag/v3.0.0).

**Comment by mahkali** [comment]
This is in regards with Semantic Versioning. See https://semver.org/

I would also suggest to release 2.9.0, reverting the namespace changes so that whomever updates within 2.9.x range, will update to the old namespace.

**Comment by globalcitizen** [comment]
> I would also suggest to release 2.9.0, reverting the namespace changes so that whomever updates within 2.x range, will update to the old namespace.

Hrrm, agreed that makes sense. Project for another day though. My time today has run out!

**Comment by mahkali** [comment]
Since 2.8.0 was already released with the new namespaces, anyone that started to use them will run into the issue of not being able to download the tag 2.8.x when installing via composer. They can revert to 2.7.x or update to 3.0. 

Releasing 2.9 would require tagging 2.8 again, so perhaps the current situation is best and leave it at that.

**Comment by globalcitizen** [comment]
Ok great.

**Comment by Ciki** [comment]
Hi @globalcitizen this is still causing problems as on [packagist.org](https://packagist.org/packages/globalcitizen/php-iban) (used by composer) there is still 2.8 version but no 3.0 version  . Maybe because you renamed the existing 2.8 tag to 3.0? Could you please bump to 3.0.1 or whatever just so it is pure new version and packagist will pull it?

Thanks

**Comment by globalcitizen** [comment]
File a bug at packagist please. You can reference this issue.

**Comment by Ciki** [comment]
it's documented there that if you just rename the tag, it is cached and will not be refreshed.. so it's rather feature than a bug. I think the correct way is to keep the original tag and issue a new release, in accordance with semver, i.e. keep 2.8, issue 2.8.1 (without namespaces) and issue 3.0.0. (with namespaces)

**Comment by globalcitizen** [comment]
Should be fixed now with v3.0.1. Please let me know if not resolved!

**Comment by Ciki** [comment]
resolved as now we can at least get v3.0.0 now, as mentioned in #105 thanks!
