### ISSUE TITLE
Version 3.0 mentioned in README.md but 2.8.0 is the last one available via composer (at the packageist.org)

### ISSUE THREAD

**Issue by abronin** [globalcitizen/php-iban#105]
It's impossible to install the package by adding `"globalcitizen/php-iban": "3.0.0"` to the `composer.json` as it described in the `README.md`.

Here is the error I got from composer:
`The requested package globalcitizen/php-iban ^3.0 exists as globalcitizen/php-iban[dev-master, v1.4.9, v1.5.0, v1.6.0, v2.0.0, v2.0.1, v2.1.0, v2.1.1, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.3.0, v2.3.1, v2.4.0, v2.4.1, v2.4.10, v2.4.11, v2.4.13, v2.4.14, v2.4.15, v2.4.16, v2.4.17, v2.4.18, v2.4.19, v2.4.2, v2.4.20, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.8.0] but these are rejected by your constraint.`

**Comment by JanWennrichPCSG** [comment]
Can confirm: Version `v2.8.0` is the latest version that is shown on packagist.org:  
![image](https://user-images.githubusercontent.com/36995809/88034118-82bd2200-cb40-11ea-9c2e-169eb5d0863f.png)  
https://packagist.org/packages/globalcitizen/php-iban  
  
The reason is probably that the packagist package isn't auto-updated (see screenshot) and was last updated before the release of version `v3.0.0`.

**Comment by globalcitizen** [comment]
Cheers will check it out.

**Comment by globalcitizen** [comment]
Just released [v3.0.01](https://github.com/globalcitizen/php-iban/releases/tag/v3.0.1). Let me know if this solves it.

**Comment by globalcitizen** [comment]
https://packagist.org/packages/globalcitizen/php-iban now shows v3.0.0 but not v3.0.1. I give up.

**Comment by Ciki** [comment]
at least we can get v3.0.0 now, thanks! :)

**Comment by Ciki** [comment]
@globalcitizen here you can setup automatic update for the package here https://packagist.org/about#how-to-update-packages

then you'll see the info on https://packagist.org/packages/globalcitizen/php-iban as shown in the image below

![phpiban](https://user-images.githubusercontent.com/342730/88455410-54f41800-ce75-11ea-9e36-eb122fb27fb8.png)

**Comment by globalcitizen** [comment]
Thanks, did that. Possibly now fixed for next time.
