### ISSUE TITLE
Missing dot for version 3.0.3 (released as 3.03)

### ISSUE THREAD

**Issue by jledrogo** [globalcitizen/php-iban#108]
Hi,
The lastest version 3.0.3 has been released with a missing dot as 3.03 instead of 3.0.3
I think it will cause troubles as composer will certainly evaluate 3.03 as 3.3.0 then next version 3.0.4 will not be considered as a newer version.
It was released only yesterday so it's maybe still time to correct it.
If it's not corrected soon, next release should directly pass to 3.3.1 to be sure it's a upper version.

**Comment by globalcitizen** [comment]
Damn OK will sort it shortly.

**Comment by globalcitizen** [comment]
Sorted.
