### ISSUE TITLE
Check for EU/EFTA/Other Countries

### ISSUE THREAD

**Issue by julianpollmann** [globalcitizen/php-iban#113]
It would be nice, if a check for non-eu countries could be implemented.
Similar to the function iban_country_is_sepa() to check if a iban belongs to a EU country or non-eu (e.g. Switzerland, Norway, Andorra).

**Comment by globalcitizen** [comment]
OK. I am very unlikely to find time to add new features to this codebase in the near future. Contributions are welcome!

**Comment by globalcitizen** [comment]
Available in __[Version 4.1.0](https://github.com/globalcitizen/php-iban/releases/tag/v4.1.0)__. Thanks.
