### ISSUE TITLE
Does it really generate IBAN?

### ISSUE THREAD

**Issue by inDeev** [globalcitizen/php-iban#115]
From documentation: `php-iban` is a library for parsing, validating and "**_generating IBAN_**" (and IIBAN)

But in documentation I'm not able to find any information, how to generate IBAN (as I have account number and bank code, and know the country). Also I didn't found anything in code.

Is this package really able to generate IBAN?

**Comment by globalcitizen** [comment]
I suggest you read about IBAN then look at the checksum correction routines.
