### ISSUE TITLE
Irland IBAN not working correctly

### ISSUE THREAD

**Issue by sirkokoenig** [globalcitizen/php-iban#118]
Hi, can somebody fix the code for the following example?
It does not extract the bank identifier:
IEXXPFSR991070XXXXXXX

I´m no expert in regex, so I can´t find the solution by myself ;)

**Comment by sirkokoenig** [comment]
Also GBXXREVO009969XXXXXXXX seems to be a problem.

**Comment by globalcitizen** [comment]
Sorry this is insufficient information to resolve your issue. Either provide the full number or there's no way to help. Perhaps try running `print_r(iban_mistranscription_suggestions($iban));` to determine potential transcription issues.

**Comment by globalcitizen** [comment]
Sorry this is insufficient information to resolve your issue. Feel free to re-open the issue if you are happy to provide the full number. Perhaps try running `print_r(iban_mistranscription_suggestions($iban));` to determine potential transcription issues.

**Comment by sirkokoenig** [comment]
> o

running this will result in an empty array, so maybe no mistranscription. An example is:
GB95REVO00996906751878
