### ISSUE TITLE
Seems offical registry format has changed.

### ISSUE THREAD

**Issue by ErikKrause** [globalcitizen/php-iban#31]
If http://www.swift.com/dsp/resources/documents/IBAN_Registry.txt is the correct URL it has changed format. '|' is not the delimiter any more, it seems to be tab ("\t") now. Furthermore the order of the fields has changed and possibly the content, too.

**Comment by globalcitizen** [comment]
I believe you may be under the impression we use the official registry's contents directly.

We do not use that file because it is riddled with errors.

You can see a summary of the issues in `docs/COMEDY-OF-ERRORS`.

If there is an issue not explained by the above, feel free to re-open.

**Comment by Erik-Krause** [comment]
Thanks! You are right, I was misled by the link in the readme.md file, sorry.
