### ISSUE TITLE
Missing Ukraine IBAN

### ISSUE THREAD

**Issue by SpikeO** [globalcitizen/php-iban#32]
The IBAN regular expression is missing for Ukraine IBAN accounts.

**Comment by globalcitizen** [comment]
Thanks, apologies for the delay, I have been in China with bad connectivity.

According to the new official SWIFT URL for the text version of the registry at https://www.swift.com/node/11971 there is no entry for Ukraine.

Similarly, the new official SWIFT URL for the PDF version of the registry at https://www.swift.com/file/5996/download?token=lf3shUpn has no entry for Ukraine.

It would appear that there is no official IBAN for the Ukraine.

**Comment by globalcitizen** [comment]
I have done some further research and according to Wikipedia at https://en.wikipedia.org/wiki/International_Bank_Account_Number#IBAN_formats_by_country the Ukraine IBAN is listed by Nordea at http://www.nordea.com/en/our-services/cashmanagement/iban-validator-and-information/iban-countries/index.html however this is not official so is not included.
