### ISSUE TITLE
Missing library version file

### ISSUE THREAD

**Issue by odalecne** [globalcitizen/php-iban#34]
VERSION file appears to have been lost in migration.

**Comment by globalcitizen** [comment]
That was part of the release process, which is currently under discussion in another open issue. It will be restored in the near future, I will leave this issue open until it happens.

**Comment by globalcitizen** [comment]
We are now using the Github based release process which provides versioning. This should be adequate.

**Comment by odalecne** [comment]
Well done. Anyway it would be perfect if the version number were stored somewhere in the code (see #16) since applications using your library should be aware of it.
Given the latest improvements you could consider to specify such information in composer.json (https://getcomposer.org/doc/04-schema.md#version) as exemplified in #30.

**Comment by globalcitizen** [comment]
I don't use composer and am unaware of an automated mechanism for publishing github releases that generates a new `composer.json` file automatically. While I could write one I don't see enough demand right now to justify it. If you'd like to do some research in to how others solve this issue you are having, or explain in detail why it is that you require the version to be specified in the code, I am willing to consider changing the release process... but it would have to be easy and compelling.

**Comment by acoulton** [comment]
@odalecne that's a bad idea - from the composer documentation you linked to (my emphasis):

> Optional if the package repository can infer the version from somewhere, such as the VCS tag name in the VCS repository. In that case **it is also recommended to omit it**.

Hardcoding versions into the composer.json adds significant extra commits and merge conflicts over time and breaks the ability to reliably detect it from branch/tag naming.

If an application *really* needs to know the exact version of the library that's present, it could parse the `composer.lock` file to detect it - but in most cases you would work the other way round: specify the version in composer.json/composer.lock and then build the application to work with the specified version.
