### ISSUE TITLE
Get BIC for an IBAN account

### ISSUE THREAD

**Issue by roelvanduijnhoven** [globalcitizen/php-iban#55]
Heads up: since I was not able to find anything about BIC in here, most likely I am doing something wrong!

It would be very helpful for me if a library (this one?) could help me obtain the bic code of the bank, given an IBAN number. I am curious about whether this possible; and what it would take.

**Comment by globalcitizen** [comment]
BIC is a SWIFT feature.

IBAN largely was invented to remove the need for BICs.

It should be possible to determine the SWIFT BIC for a bank from its IBAN prefix, however there is no public, free, up to date database for this. There exists paid services for this, and lots of random lists of dubious quality.

Hope that helps.

**Comment by roelvanduijnhoven** [comment]
Damn; I just *now* found that setting the BIC in the payment gateway that we use is optional :). Thanks!

**Comment by ericsala** [comment]
Do you know any "paid service" or API to do this ?
Thnk you! :-)

**Comment by globalcitizen** [comment]
SWIFT provides the data for a fee.
