### ISSUE TITLE
Cant find generate methods

### ISSUE THREAD

**Issue by nancorrea** [globalcitizen/php-iban#56]
Hi, at the descripiton you wrote there this library also generate the IBAN codes, how can I do it? I didnt find anything like at the documentation or code

**Comment by globalcitizen** [comment]
What is your expected input and output?

You can generate an IBAN at a pinch like this:

```
# first, build the IBAN you want with a blank checksum
$bban = $country . $specific . $bits . $here;
$iban = $country . '00' . $bban;
# then set the checksum
iban_set_nationalchecksum($iban);
```

Does that solve your use case?

**Comment by globalcitizen** [comment]
No response in 24 hours, closing.

**Comment by nancorrea** [comment]
I took off the $country parameter from $bban variable and I think it worked

```
$country = 'DK';
$bank_number = '4420';
$account_number = '3161123456';

$bban = $bank_number . $account_number; 
$iban = $country . '00' . $bban;
$iban = iban_set_checksum($iban); ## results: DK5944203161123456

debug($iban);
exit;
```

Same result as: https://www.iban.com/calculate-iban.html

**Comment by globalcitizen** [comment]
Oh yeah sorry that was my error 👍  Glad you got it working.
