### ISSUE TITLE
Different output on wrong IBAN at MachineFormat & HumanFormat

### ISSUE THREAD

**Issue by julianwue** [globalcitizen/php-iban#57]
When I use a correct IBAN, I get on both methods (MachineFormat & HumanFormat) an output. The Human one is with the spaces after 4 characters. The MachineFormat is the one without spaces.

If I change to a wrong IBAN - e.g. wrong Checksum, then I get only a result at MachineFormat, and the Human output is empty. But there should be also an output, even its wrong.

Iban is set with standard $machine_format_only=false

**Comment by julianwue** [comment]
At php-iban.php:64 you check the validity. Should be consistent and removed. In my opinion it´s the programmers task to validate if its correct. Here it´s only about an output in a special format.

**Comment by globalcitizen** [comment]
I agree this is inconsistent and should be resolved.

I have uploaded a fixed version to git HEAD, however I am not going to do a full release for this change. It will be integrated in to the next release.

Thanks for taking the time to write it up. 👍
