### ISSUE TITLE
How to verify SWIFT/BIC input?

### ISSUE THREAD

**Issue by drizzersilverberg** [globalcitizen/php-iban#60]
I am able to verify IBAN input in laravel with this code:

`<?php 
use IBAN;
$iban = new IBAN("FR7630001117941234561111111");
$result = $iban->verify();
?>`

But how I can verify SWIFT/BIC input?

**Comment by globalcitizen** [comment]
The library is for IBAN.

SWIFT BIC are a separate system, used for international transfers.

In general, if an account is within Europe, you only need the IBAN and not the SWIFT details.
