### ISSUE TITLE
Account number in hungary is wrong

### ISSUE THREAD

**Issue by djereg** [globalcitizen/php-iban#64]
```
array (size=7)
  'checksum' => string '98' (length=2)
  'bban' => string '109180010000000xxxxxxxx3' (length=24)
  'bank' => string '109' (length=3)
  'country' => string 'HU' (length=2)
  'branch' => string '1800' (length=4)
  'account' => string '10000000xxxxxxxx3' (length=17)
  'nationalchecksum' => string '3' (length=1)
```

Bank is OK (109), branch is OK (1800), but the account is too long. The first `1` is the checksum of first 7 (bank+branch) numbers, and the account is the next 16 (15+1 checksum) numbers.

In Hungary the bank account numbers are 2x8 or 3x8 length, and the first 8 is the bank+branch+checksum and the next 8 (or 16) is the account.

**Comment by globalcitizen** [comment]
First, thanks for the bug report!

Apologies for the slow response ... I was traveling over the weekend.

About the checksums, non-IBAN checksums are considered part of the BBAN.

First of all, we should clarify that there are two uses of 'account':

1. 'account' meaning the whole BBAN except the bank and branch parts, but including any national checksum.
2. 'account' meaning the account number portion only as specified by the bank

From reading your example I understand that you mean to obtain number 2. I think the library as it is written only ever supplies number 1.

Anyway in the string you supplied and the example that you gave you seem to be saying that the library is wrong in two places:

- It's not giving you what you expect for account (you wanted `0000000xxxxxxxx3` but you got `10000000xxxxxxxx3`)
- It's not picking out the right national checksum (you claimed it is the `1` after the branch, but it thinks it is the final `3`)

Can you please give me your thoughts on the above before I continue?

**Comment by djereg** [comment]
Ahh, now I understand, how the library works, so this is not actually bug.

I thought that the `iban_get_account_part()` returns the account number without checksums, but I missed something, included the last `3` (in example) what is checksum too, not part of the account number.

In Hungary the BBAN structure is `3!n4!n1!n15!n1!n`

If the BBAN is `109180010000000xxxxxxxx3` then
`iban_get_bank_part()` returns `109` OK
`iban_get_branch_part()` return 1800` OK

I thought that `iban_get_account_part()` will return only the `15!n` part, what is `0000000xxxxxxxx`.

I don't know what is the BBAN structure in other countries, and in fact, now in my case the account number is not important, only the bank and the branch, but...

I think it is a bit difficult getting the only/correct/real account number in all countries, depending on different BBAN structures.

**Comment by globalcitizen** [comment]
OK great. Glad you are clear 👍
