### ISSUE TITLE
Issue with morocco IBAN

### ISSUE THREAD

**Issue by BastienMottier** [globalcitizen/php-iban#65]
Hi,

The library check if morocco IBAN has 26 digits with the MA prefix.

But, I have some members on my website who register with a 24 digits IBAN. [After search, HSBC say than an Morocco IBAN has 24 digits (with the MA prefix).](http://www.hsbc.fr/1/2/hsbc-france/particuliers/banque-au-quotidien/pays-iban)

Is there a bug ? Where have you found your informations for Morocco IBAN ?

**Comment by globalcitizen** [comment]
Thanks for the bug report.

Morocco is not an official IBAN country, so there is actually no standard.

I can see some examples online saying 24, 26 and 28 digits:

- 2017: [IBAN.com](https://www.iban.com/structure.html) (28) 
- 2016: [HSBC](http://www.hsbc.fr/1/2/hsbc-france/particuliers/banque-au-quotidien/pays-iban) (26)
- 2011: [Bug report](https://github.com/iulianu/iban-tools/issues/1) (26)

I think unless we can find an authoritative source, it is not worth modifying the current settings.

**Comment by globalcitizen** [comment]
Insufficient information.
