### ISSUE TITLE
Problem with Bulgarian IBAN

### ISSUE THREAD

**Issue by ivelindobrev** [globalcitizen/php-iban#66]
Hello guys,

   I've problem with this IBAN not validating: BG75TTBB9400C127729455
   It validates if using online validator like https://www.ibancalculator.com/.
   I've triple checked with the bank and the account is the same (there are not errors).

Thanks

**Comment by globalcitizen** [comment]
Thanks for the report. I am extremely busy right now but will get to it in time.

**Comment by globalcitizen** [comment]
Upon quick review it seems...

```
BG75TTBB9400C127729455 ... FAILED (does not match regex /^BG(\d{2})([A-Z]{4})(\d{4})(\d{2})([A-Za-z0-9]{8})$/ for country BG)
```
The portion which does not match is the two digit national checksum, ie. `(\d{2})`

For all of the other example IBANs, this matches. However, for your IBAN this is `C1` which is not two digits.

It seems the original BBAN specification including national checksum was either wrong or has now been considered out of date and alphanumeric characters are now permitted.

To further investigate could you please supply the bank name and year of account opening?

**Comment by globalcitizen** [comment]
Insufficient information.
