### ISSUE TITLE
Validation passes if the iban starts with "IBAN"

### ISSUE THREAD

**Issue by zelding** [globalcitizen/php-iban#67]
Somehow this one is considered valid `IBANBE87738004265594`

**Comment by globalcitizen** [comment]
Yes, that's a feature not a bug. If you want a strict check use a different function.

**Comment by zelding** [comment]
Ahh that wasn't clear, thank you!

**Comment by globalcitizen** [comment]
You can also add a new argument to the main function I think...

<img width="650" alt="screen shot 2017-12-04 at 22 28 38" src="https://user-images.githubusercontent.com/505366/33557554-8aafa44e-d942-11e7-8514-6ea741212de3.png">
