### ISSUE TITLE
PHP Warning on empty input

### ISSUE THREAD

**Issue by marcovo** [globalcitizen/php-iban#68]
When passing an empty string to `verify_iban()`, PHP will throw a warning if the `gmp` extension is used. (When `gmp` is not used, the warning does not show up because of an alternative path taken.)

Steps to reproduce:
 - Make sure `gmp` is activated (`function_exists('gmp_intval')`)
 - Run the following:
```
require("vendor/autoload.php");
var_dump(verify_iban(""));
```
Result (tested on v2.6.1 and v2.6.4):
```
PHP Warning:  gmp_init(): Unable to convert variable to GMP - string is not an integer in ***/vendor/globalcitizen/php-iban/php-iban.php on line 151
bool(false)
```

Expected result:
```
bool(false)
```

When passing a single-character string (e.g. "a") no warning is shown. Probably the warning can be prevented by simply checking `if(empty(...)) return false;` somewhere?

**Comment by globalcitizen** [comment]
Nice catch. Verifying now. Will push out a fix shortly with credit to you.

**Comment by marcovo** [comment]
Thanks for the fast response :) .
