### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gemal** [globalcitizen/php-iban#83]
Any chance for a new release with those latest changes since last release

**Comment by globalcitizen** [comment]
Reasonable request. I am super busy. Sort of looking for a replacement maintainer, since I no longer work directly with this sort of thing (more so in China). Will put this in the "open browser tabs" informal workqueue to remind myself to get it done maybe over the weekend.

**Comment by globalcitizen** [comment]
Here you are sir!

https://github.com/globalcitizen/php-iban/releases/tag/v2.7.0
