### ISSUE TITLE
PHP 7.4: The array and string offset access syntax using curly braces is deprecated

### ISSUE THREAD

**Issue by bwurst** [globalcitizen/php-iban#86]
When using php-iban with PHP 7.4 beta I get this errors:

`Deprecated: Array and string offset access syntax with curly braces is deprecated in php-iban.php on line 737`
`Deprecated: Array and string offset access syntax with curly braces is deprecated in php-iban.php on line 738`
`Deprecated: Array and string offset access syntax with curly braces is deprecated in php-iban.php on line 741`

Please simply replace them with square braces, this is the preferred syntax.

**Comment by globalcitizen** [comment]
Happy to accept a pull request.

**Comment by bwurst** [comment]
Done so. See #87

**Comment by globalcitizen** [comment]
Thanks!
