### ISSUE TITLE
not validating bank account number, iban should be invalid

### ISSUE THREAD

**Issue by poolerMF** [globalcitizen/php-iban#90]
I tried php-iban, but I don't think it's working good
SK91 8330 0000 0023 0067 2100 is invalid by https://www.ibancalculator.com/iban_validieren.html
php-iban says it's valid

**Comment by globalcitizen** [comment]
Thanks for reaching out.

* What is the origin of that IBAN?
* The [current SK test IBANs](https://github.com/globalcitizen/php-iban/blob/master/utils/example-ibans/sk-ibans) return results as expected. Therefore, I am confident they are correct and the code is correct.
* I get the result from `verify_iban()` for your IBAN that it is OK but `iban_verify_nationalchecksum()` to check the national checksum (pre-IBAN system) fails.
  * To me, this suggests that it may be a valid IBAN but the IBAN is relatively new, the older (pre-IBAN national checksum) system is no longer in use, and therefore it fails that check, but this is OK.
  * This is why we have them as different functions.

Feel free to re-open the issue if you find further evidence of issues.
