### ISSUE TITLE
Suggestion for autoloading improvements (global namespace pollution)

### ISSUE THREAD

**Issue by kfb-ts** [globalcitizen/php-iban#95]
(Related to #89, I commented there first, but a new issue seems more appropriate)

Hi there

While there's probably no issue regarding performance when always loading both files, the pollution of the global namespace is an issue (mostly) in bigger projects.
If all functions were prefixed with _iban that'd be less of a problem, though still annoying. But functions like `_italian()` are, for one, unclear in their behavior and might also easily lead to conflicts.

So I'm wondering whether you'd be open for improvements in that direction, even if they'd introduce breaking changes. I'd be happy to actually implement them.

These would be some of the options for the procedural code:
- Add iban prefixes to all functions (besides verify_iban) and move global flags into the related functions, so they don't pollute until they're being used
- Get rid of the procedural code
- Remove the procedural code from autoloading

And for the OOP code:
- Use the composer classmap setting instead of the file autoloading. It's basically lazy autoloading for the class file and has almost no negative side effect, unless someone would be doing some weird things with the autoloader configuration
- Use a namespace and PSR4 (E.g. GlobalCitizen/PhpIban)
  - This would mean dropping support for PHP < 5.3, but composer itself doesn't support PHP < 5.3.2
  - An alternative would be to provide both, classes with namespaces for autoloading and classes without that aren't being autoloaded

**Comment by globalcitizen** [comment]
Complex solution to non-problem I have no interest to test/support.

**Comment by L00Cyph3r** [comment]
Such a shame the owner is too ignorant to listen for improvements.. Well I guess his name allows him to pollute the 'global' namespace..
