### ISSUE TITLE
PHP array registry would be more efficient

### ISSUE THREAD

**Issue by Bilge** [globalcitizen/php-iban#98]
The IBAN registry is currently stored in a text file which is parsed each time it is loaded. This has a significant overhead compared with [array config](https://github.com/mrkrstphr/array-config). The advantages of using an array:

* No need to parse anything. All line and pipe-separator parsing code can be deleted.
* Registry can be cached by PHP automatically using opcache.
* Loads faster.
* More maintainable (no more very long lines).

**Comment by globalcitizen** [comment]
I agree, it could be enhanced performance wise. 

However, people depend on the current format.

If you submit a PR that caches the current format in an intermediate format without introducing dependencies I would consider it.

**Comment by Bilge** [comment]
Why would anyone depend on the current file format? They should use the
library's API, not the file directly.

**Comment by globalcitizen** [comment]
90% of the life of software is maintenance. As a maintainer, it is my job to care about such things to save other people hassle.

**Comment by Bilge** [comment]
I don't think we're even talking about the same thing at this point.
